### ISSUE TITLE
Album title/Artist name sometimes cut off after first letter

### ISSUE THREAD

**Issue by jneidel** [AdrienPoupa/VinylMusicPlayer#126]
Since the last fdroid release (0.20.1), I've had cut off titles (album/artist).

## Artist

**Cut off**
<img height=500px src="https://user-images.githubusercontent.com/25589715/55101343-31279300-50c4-11e9-8246-793fc7ca845f.png">
**Normal**
<img height=500px src="https://user-images.githubusercontent.com/25589715/55101380-44d2f980-50c4-11e9-8b7d-639140141dcc.png">

## Album

**Cut off**
<img height=500px src="https://user-images.githubusercontent.com/25589715/55101750-1c97ca80-50c5-11e9-96bd-67e9720c543d.png">
**Normal**
<img height=500px src="https://user-images.githubusercontent.com/25589715/55101795-33d6b800-50c5-11e9-80f9-7361d4f9227f.png">

## Observations

This does not happen for all artists or albums and not all the time. I could not spot a pattern as to what causes some artists name to be cut off.
After clicking through a few albums arists, those cut of earlier will normally display again.

## Versions

Vinyl: 0.20.1
Android: 7.0

**Comment by soncaokim** [comment]
I'm experiencing this as well, with the latest master version.


On 27 Mar 2019 at 19:25, <Jonathan Neidel <notifications@github.com>>
wrote:

Since the last fdroid release (0.20.1), I've had cut off titles
(album/artist).
Artist

*Cut off*
<https://user-images.githubusercontent.com/25589715/55101343-31279300-50c4-11e9-8246-793fc7ca845f.png>
*Normal*
<https://user-images.githubusercontent.com/25589715/55101380-44d2f980-50c4-11e9-8b7d-639140141dcc.png>
Album

*Cut off*
<https://user-images.githubusercontent.com/25589715/55101750-1c97ca80-50c5-11e9-96bd-67e9720c543d.png>
*Normal*
<https://user-images.githubusercontent.com/25589715/55101795-33d6b800-50c5-11e9-80f9-7361d4f9227f.png>
Observations

This does not happen for all artists or albums and not all the time. I
could not spot a pattern as to what causes some artists name to be cut off.
After clicking through a few albums arists, those cut of earlier will
normally display again.
Versions

Vinyl: 0.20.1
Android: 7.0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AdrienPoupa/VinylMusicPlayer/issues/126>, or mute the
thread

**Comment by soncaokim** [comment]
Jonathan, can you please confirm that this behaviour is observed on Album
and Artist details, but not on Genre nor Playlist page



On 27 Mar 2019 at 19:25, <Jonathan Neidel <notifications@github.com>>
wrote:

Since the last fdroid release (0.20.1), I've had cut off titles
(album/artist).
Artist

*Cut off*
<https://user-images.githubusercontent.com/25589715/55101343-31279300-50c4-11e9-8246-793fc7ca845f.png>
*Normal*
<https://user-images.githubusercontent.com/25589715/55101380-44d2f980-50c4-11e9-8b7d-639140141dcc.png>
Album

*Cut off*
<https://user-images.githubusercontent.com/25589715/55101750-1c97ca80-50c5-11e9-96bd-67e9720c543d.png>
*Normal*
<https://user-images.githubusercontent.com/25589715/55101795-33d6b800-50c5-11e9-80f9-7361d4f9227f.png>
Observations

This does not happen for all artists or albums and not all the time. I
could not spot a pattern as to what causes some artists name to be cut off.
After clicking through a few albums arists, those cut of earlier will
normally display again.
Versions

Vinyl: 0.20.1
Android: 7.0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AdrienPoupa/VinylMusicPlayer/issues/126>, or mute the
thread

**Comment by jneidel** [comment]
> can you please confirm that this behaviour is observed on Album and Artist details, but not on Genre nor Playlist

It happend neither for Genres nor Playlists.

**Comment by soncaokim** [comment]
For information, I've attempted reverting the following commits: ba0dfae7dd03771f3625b8393927986aad552e2a, 05cdc7c8414a256dfdf8ce1dfc79fa2c3bc3cfaa and e8dc9379105c9091597a4eeb4c96cc00f8be3259.

The regression is gone.

The commits are quite big, havent narrowed it down yet. May be @AdrienPoupa or @theduffmaster  can help pinpoint where the problem is?

**Comment by AdrienPoupa** [comment]
I'm not sure why, but my latest commit seems to help. Please try it and let me know if it fixed it for you

**Comment by soncaokim** [comment]
Looks good with 7b0327c6 on vinyl/master

**Comment by AdrienPoupa** [comment]
Feel free to reopen if it persists
