### ISSUE TITLE
Some artist names won't show in artist list

### ISSUE THREAD

**Issue by siSSSou** [AdrienPoupa/VinylMusicPlayer#170]
**Describe the bug**
Artist names with parentheses, such as "Sunn O)))", won't show in the artists tab.
I can't neither find the artists with search function or access it with songs or album lists : it seems it can't be imported

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J5 2016
 - Android Version: 9
 - ROM: Bootleggers
 - Vinyl Music Player Version: 0.22.1

**Additional context**

**Comment by soncaokim** [comment]
Hi

Is the corresponding song still visible in the app?
Is the same issue spotted with another music player (i.e. Shuttle)

**Comment by siSSSou** [comment]
I made a mistake  : this name shows up in artist list !
But I had to manually add songs one by one : checking the music folder had no effect...

**Comment by soncaokim** [comment]
I dont get what you mean by "adding song one by one".

Vinyl and some other music players rely on a facility operated by the Android OS. This facility scans for the songs on the device (all of them), gives the resulting list to the music players and apps like Vinyl is only doing the display bits.

Missing song/artist/etc can be originated in music player and/or in the said Android facility.

That's why I asked the question: Is the same issue spotted with another music player (i.e. Shuttle)?

**Comment by siSSSou** [comment]
> Vinyl and some other music players rely on a facility operated by the Android OS. This facility scans for the songs on the device (all of them), gives the resulting list to the music players and apps like Vinyl is only doing the display bits.

I think that is the problem on my system.
Sorry for having incriminated Vinyl too quickly ;-(

**Comment by soncaokim** [comment]
Hope that you will sort that out.
