### ISSUE TITLE
Notify prior to addition of duplicate song to a playlist

### ISSUE THREAD

**Issue by dronewizard** [AdrienPoupa/VinylMusicPlayer#178]
Currently there is no way of knowing if songs are already in large playlists without scrolling the entirety of it to check manually. I am proposing a notification that makes users aware that a song is already in a playlist if they are trying to add another instance of it (most likely unintentionally).

**Comment by dronewizard** [comment]
Please see this fork that accomplished it successfully https://github.com/Sogolumbo/Phonograph

**Comment by AdrienPoupa** [comment]
@Sogolumbo feel free to open a PR here

**Comment by Sogolumbo** [comment]
Nice to know that someone noticed my efforts. 
Unfortunately github doesn't allow me to compare my fork to yours to create a PR. 
By the way: I need some help on this feature because I don't know anything about material design and I would like to have a proper placing of the checkmark (currently it is just added to the playlist name).

**Comment by Cantuariensis** [comment]
@Sogolumbo I can do a visual mockup of the checkmark placing. Or do you need help for the actual implementation?

Adding duplicates in playlists is for me the biggest issue so far with Vinyl so I switched to Eon. As Eon is another Phonograph fork, we should be able to find the source code and how they implement that feature. If anyone as insights :)

**Comment by Cantuariensis** [comment]
I also think that the scenario could be better like this:
- User wants to add 1 or more songs NOT already in the playlist => added in the playlist
- User wants to add 1 or more songs already in the playlist => user is asked to choose between _Add one more time_ or _Remove_ or _Do nothing_.
- User wants to add 1 or more songs with some of them already in the playlist and some others NOT already in it => songs not already in the playlist are added, and user is asked to choose between  _Add one more time_ or _Do nothing_ for the songs that are already in it.

**Comment by Cantuariensis** [comment]
So far I found design references in Google Translate and Facebook Messenger for that kind of list:
![73273b433b2ef5792316c91d44077d](https://user-images.githubusercontent.com/62208363/90043263-288d2800-dccc-11ea-9005-8a18369c4fae.png)

Working on that and with Material Design guidelines, here are a few ideas (clic to see HD picture)
![6d88c231cd74074a25342750978d23](https://user-images.githubusercontent.com/62208363/90043332-3e025200-dccc-11ea-9af5-74fd293795b2.png)

Let me know what do you think!

**Comment by Sogolumbo** [comment]
Hello @Cantuariensis,
Thanks for your Mockups. Just like you I would also use the checkmark design (similar to the facebook design but with squares instead of the circle). But what about adding multiple songs to a playlist? How would you display that only some of the songs are in that playlist?

I also think that deleting a song or a number of songs should be part of the same dialog. That's why checkmarks would be so useful.

The picture which you call my proposal is not really a design proposal but rather a snapshot of what I was able to make. I don't know if you have any experience with programming in material design in android. I know how to program simple stuff in material design. But phonograph creates the designs generically and is very modular. That makes things much more complicated for me. So much that I don't even know where to start adding code for the checkmarks. I found the place where the playlists are getting queried and just added the checkmarks to playlist names.

Duplicate songs in playlists is a difficult topic. I think the best options are:
- Ask the user everytime about adding duplicates.
- Never ask the user but introduce a setting.
- Ask the user. The user can select the answer and click on `One time` or `Always`. It might make sense to save this answer per playlist.

**Comment by soncaokim** [comment]
@Sogolumbo I'd suggest you to start looking https://github.com/AdrienPoupa/VinylMusicPlayer/blob/93ee720947bfe0fa7dd301c1f8acbb263a03e789/app/src/main/java/com/poupa/vinylmusicplayer/dialogs/AddToPlaylistDialog.java

Note that this is called in multiple situation (adding 1 song, adding multiple songs) so you want to have a look at the caller sites as well.

**Comment by Sogolumbo** [comment]
@soncaokim I've been in that file but I don't know how the MaterialDialog.Builder works.
Seems like it's easy to do a multiple choice dialog:
https://android.googlesource.com/platform/external/AntennaPod/afollestad/+/12af7aed1a6f2031574545fdd055f451229d20f9/README.md#multi-choice-list-dialogs
But we need an additional button to create a new playlist which is not a checkmark.
Maybe I'm gonna look into it again. That site might give me more answers.

**Comment by Cantuariensis** [comment]
@Sogolumbo Following [Material Guidelines regarding checkboxes](https://material.io/develop/android/components/checkboxes), here is how we could do the 3 states (unselected, some selected, all selected).
![87a1c58eca5e66d1d25f16faf3fbee](https://user-images.githubusercontent.com/62208363/90812873-0ed08e00-e327-11ea-8470-463a7fd7198c.png)
Note: it's OK to put the check-boxes on the right side, Google is actually doing that in a few places, like the per app notifications settings inside the Settings app. But maybe we should _not_ use bold text (and that would make the code much simpler).

And no, sadly I don't have experience at all in Android. I wish I could help more!

**Comment by Sogolumbo** [comment]
This issue isn't resolved yet.
