### ISSUE TITLE
Scrolling Crashing App - Artists Tab

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [AdrienPoupa/VinylMusicPlayer#183]
**Description of bug** 

If you scroll through the artists tab quickly and hit the bottom 3/4 of the results, it consistently causes a full crash. 

**How to replicate** 

1. Open application
2. Navigate to artists tab
3. Rapidly scroll down through artists

**ROM** 

Lineage OS/Android 9

**Other comments**

It doesn't seem to affect any other tab in the app, just artists.

**Comment by soncaokim** [comment]
Can you please provide the app version?

**Comment by Nathan-Nesbitt** [comment]
@soncaokim the app version is 0.22.1

**Comment by soncaokim** [comment]
actually this looks similar to https://github.com/AdrienPoupa/VinylMusicPlayer/issues/166 and the fix is not released.

Its originally due to LastFM policy change, which affects the way the artist image is fetched. 

I guess @adrienpoupa is still not happy of how this can be solved, or just lack of time to look into it, to prepare a release.

**Comment by AdrienPoupa** [comment]
The fix is good, I just need to draft a new release, thanks for the reminder :)

**Comment by Akito13** [comment]
@AdrienPoupa How's it going?

**Comment by Nathan-Nesbitt** [comment]
@Akito13 It looks like there has been a fix pushed for this (see #167 ) but they haven't created a new release. @AdrienPoupa is there a planned date for the next release?
