### ISSUE TITLE
Importing Playlists Twice

### ISSUE THREAD

**Issue by trymeouteh** [AdrienPoupa/VinylMusicPlayer#187]
**Describe the bug**
I did some fiddling around with Vinyl and what I learn was that when your boot your phone, it will scan your device for playlist files such as m3u files and import them into Vinyl and it will also show the playlist file itself in vinyl.

**To Reproduce**
1. Create a playlist in Vinyl
2. Save the playlist as a m3u file on your device
3. Restart your phone
4. Launch Vinyl and you will see two playlists with the same name listed in Vinyl

**Expected behavior**
I did not expect my playlist to be imported twice

**Screenshots**

**Smartphone (please complete the following information):**
 - Samsung Galaxy S8
 - Android Version: 9
 - ROM:Stock ROM
 - Vinyl Music Player Version:0.22.1

**Additional context**
Please disable the automatic importing of playlists and instead add a feature to manually import playlists.

**Comment by Cantuariensis** [comment]
Agree, very frustrating. In my case it happens when I exports playlists from Vinyl and then reboot. The _playlists_ list will show the previous playlists and will also import the previously exported one. The result is duplicated identical playlists.

Not sure if this is something in the scope of Vinyl though. As far as I know, this is a common problem for all Android apps using the system music library.
**Can someone here confirm if this is still an open issue or not?**
