### ISSUE TITLE
Cannot reorder currently played track

### ISSUE THREAD

**Issue by defvs** [AdrienPoupa/VinylMusicPlayer#189]
**Describe the bug**
Up Next list doesn't allow me to reorder the currently played track (the one with the sound icon) like phonograph used to allow me
It is very useful when you want to skip a bunch of random songs, you move the currently played song up before the track you want played next.

**To Reproduce**
1. Play any list of multiple tracks
2. Try to move the currently played track in the player by drag and dropping the "number" which is actually an icon for the currently played track

**Expected behavior**
Should move like the other tracks should.

**Smartphone (please complete the following information):**
 - Device: Umidigi One Max
 - Android Version: 9.0
 - ROM: phh GSI
 - Vinyl Music Player Version: 0.22.1

**Comment by bertin0** [comment]
I am also being affected by this. It seems that the currently playing icon decoration is interfering with the drag to reorder functionality. Sometimes, the decoration stops working and then I can reorder the currently playing song. I would guess that that icon is obstructing the touch target of the underlying 0 number which allows dragging. A simple fix would be to add a switch to disable the decoration altogether (not just the animation but the static icon too)

**Comment by bertin0** [comment]
After some investigation the issue seems to be the fact that the imageText visibility gets set to GONE for the currently playing song (here):https://github.com/AdrienPoupa/VinylMusicPlayer/blob/11d858d61db375fe3eb8f2242cc37dc52d4d3799/app/src/main/java/com/poupa/vinylmusicplayer/util/PlayingSongDecorationUtil.java#L117-L119

The issues seems to go away if we change it to View.INVISIBLE. I would open a PR, but I'm not sure if changing it to invisible would be also ok for that second case where showAlbumImage is true.
