### ISSUE TITLE
Random genres generated

### ISSUE THREAD

**Issue by Nathoufresh** [AdrienPoupa/VinylMusicPlayer#209]
**Describe the bug**
I tag my mp3 s to have some "genre playlists". But some unknown genre are displayed. Have a look at those screenshots. 

**To Reproduce**
1. Go to " genre " tab
2. See some wrong genre are displayed.

**Expected behavior**
Only existing genre should be shown. 

**Screenshots**

![Screenshot_20191104-154724_Vinyl_Music_Player](https://user-images.githubusercontent.com/39437515/68130394-91649a00-ff1b-11e9-8cc2-077abb33a252.png)
![Screenshot_20191104-154749_Vinyl_Music_Player](https://user-images.githubusercontent.com/39437515/68130393-90cc0380-ff1b-11e9-81d8-4b434dd0030c.png)
![Screenshot_20191104-154801_Vinyl_Music_Player](https://user-images.githubusercontent.com/39437515/68130395-91649a00-ff1b-11e9-8b7c-a7b73b4c8c8e.png)

**Smartphone (please complete the following information):**
 - Device: Pocophone F1
 - Android Version: 9.0
 - ROM: LineageOS 16.0
 - Vinyl Music Player Version: 0.22.1 (F-Droid)

**Comment by Nathoufresh** [comment]
I figured out it is related to media store. I just cleared the media store's data and reboot and now it's way better.

**Comment by minhja** [comment]
I suggest to reopen this issue. I have the same problem, and just copied and modified @Nathoufresh 's comment here.

**Describe the bug**
I tagged my m4a's to have genres. In Vinyl the genres appear as random numbers. e.g. 13 in place of "Pop", 17 instead of "Rock", 20 instead of "Alternative", 24 instead of "Soundtrack" and 77 instead of "Musical".

**To Reproduce**
Go to " genre " tab
See some wrong genres are displayed.

**Expected behavior**
"Pop", "Rock", "Alternative", "Soundtrack" and "Musical" appear as genres instead of random numbers.

**Screenshots**
![Screenshot_20200627-004318](https://user-images.githubusercontent.com/4073849/85907180-eb023780-b810-11ea-9991-9c6548bee382.png)

@Nathoufresh : how did you clean the Media Store data? I do not know the location of this...

**Comment by Nathoufresh** [comment]
Search in the settings for "media", you'll find an app called "Media Storage", just clear the storage.

It helped a bit but there were still issues. So I decided to change my workflow: if you store your songs in folders (a folder is a genre) media store will parse them as albums. It's definitely not perfect but usable, at least for me because I don't care about albums... So I use "albums" as playlist.

**Comment by minhja** [comment]
@Nathoufresh Thanks for your reply. I discovered that it is a 'bug' of the Android media scanner, that assigns genre numbers according to id3v1 genre lists ([https://en.wikipedia.org/wiki/List_of_ID3v1_Genres]) instead of providing genre names. This means most if not all Android music players have this issue (!). 

So it is not a bug of Vinyl. It would be interesting if there is parser that converts the genre numbers into the genre names that will show in the app.

**Comment by jkoan** [comment]
Hot the same issue on Oneplus Nord (Android 10). Why is this Bug closed if a solution was never found?

**Comment by Nathoufresh** [comment]
> Hot the same issue on Oneplus Nord (Android 10). Why is this Bug closed if a solution was never found?

@jkoan have your read the previous comments? This is not a Vinyl bug but an android media store one.

**Comment by jkoan** [comment]
Yes, i have read all comments to this issue. But within the "edit Tags" the right Genre is shown (for example Pop) but the Genre is called 13, so there must be some kind of solution. Also interestingly i have exactly one Title which is Categorized under the Genre "Pop" but also 86 ones which are in 13.

**Comment by jkoan** [comment]
With 1.0.0 the genres tab is now fixed, thx :smiley:
