### ISSUE TITLE
Deleted artist still are listed, and music is unplayable

### ISSUE THREAD

**Issue by toniz4** [AdrienPoupa/VinylMusicPlayer#315]
**Describe the bug**

**To Reproduce**
1. Delete artist
2. See that ir still are listed

**Expected behavior**
Deleted artists should not be listed

**Screenshots**
![Screenshot_20201012-174154_Vinyl_Music_Player](https://user-images.githubusercontent.com/14265358/95788627-4702a600-0cb2-11eb-96f0-2e9db4ba9ab2.png)
![Screenshot_20201012-174207_Vinyl_Music_Player](https://user-images.githubusercontent.com/14265358/95788854-b7112c00-0cb2-11eb-9d73-006799025790.png)

**Smartphone (please complete the following information):**
 - Device: Pocophone f1
 - Android Version: 10
 - ROM: Lineage os 17.1 microg
 - Vinyl Music Player Version: 0.23.1 (having the same problem as #310 the problem is still present in the latest version)

**Additional context**
I already cleared the app cache.

**Comment by Tom4tot** [comment]
I think it's not related to the app directly but how mediastorage works on Android. If you delete this app's data everything will load again and the deleted artist won't show up anymore. I've noticed that if you change the tags of a song, it will still show up under both genres (for example hip-hop and hip hop).

I don't know if it can be fixed from the app directly.

**Comment by soncaokim** [comment]
> I think it's not related to the app directly but how mediastorage works on Android. If you delete this app's data everything will load again and the deleted artist won't show up anymore. I've noticed that if you change the tags of a song, it will still show up under both genres (for example hip-hop and hip hop).

Replying **only** on the genre issue: this should be fixed in the upcoming version, since we dont rely on the mediastore for genre info anymore.

In general, yes we are still dependent on the mediastore for the list of tracks. I'm in the process of proposing a way to get rid of it (there are many limitations/bugs due to the current Android implementation, since several OS releases), but we are not there yet.

**Comment by soncaokim** [comment]
To follow-up on this: I've made an attempt to fix this issue (see pull request https://github.com/AdrienPoupa/VinylMusicPlayer/pull/358) - but the solution is not satisfactory.

The "zombie" tracks are due to the fact that they are still accounted for in Android's MediaStore. 

While I've managed to build a cache that is a clone of MediaStore index, minus the zombies, several views - Song and Playlist for ex - still rely closely to the data fetch directly from MediaStore.

Due to the widespread dependance on this (buggy) index, works need to be carried first to reduce the dependency before this issue can be solved.

Sorry, this work will be suspended for now - at least from my end.
