### ISSUE TITLE
[Bug] Album is sorted by artist instead of album artist

### ISSUE THREAD

**Issue by IHASASUSHI** [AdrienPoupa/VinylMusicPlayer#323]
Album does not divide tracks by the album artist. i.e. album contains 2 artists under the same album artist, there will be 2 instances of the album separated by the artist, one will contain the album cover the other will not

Unsure how reproduction

-

Device info:
---
<table>
<tr><td>App version</td><td>1.0.0</td></tr>
<tr><td>App version code</td><td>172</td></tr>
<tr><td>Android build version</td><td>WW_user_100.10.107.87_20200520</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.191008.001.WW_user_100.10.107.87_20200520 release-keys</td></tr>
<tr><td>Device brand</td><td>asus</td></tr>
<tr><td>Device manufacturer</td><td>asus</td></tr>
<tr><td>Device name</td><td>ASUS_Z01R_1</td></tr>
<tr><td>Device model</td><td>ASUS_Z01RD</td></tr>
<tr><td>Device product name</td><td>WW_Z01RD</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by lufazim** [comment]
I'm having the same problem since the last update

**Comment by jfmcbrayer** [comment]
I'd like to expand on this rather than opening a new issue. There are several metadata-related issues in the latest release. The issue with track name being shown instead of artist name is now fixed. However, there are other problems.

1. Albums with multiple artists are split up into one album per unique combination of artists, with only one having the album art.
2. If you sort albums by artist, these pseudo albums get sorted separately.
3. This may be unrelated, but for albums with multiple discs, the tracks are interleaved 1.1, 2.1, 1.2, 2.2 etc instead of sorting by disc 1 then disc 2.

**Comment by jneidel** [comment]
MusicBrainz puts the `feat. xyz` in the artist tag of a song, which then leads to the above described splitting up of albums for each track with a different feature. Which makes the app essentially unusable.

**Comment by soncaokim** [comment]
Version 1.0.0 introduces a new tagging library, isolated from the Android MediaStore (since there is several known bugs that exists since years without fix with MediaStore).

Unfortunately, with v1.0.0, there is no support for album artist. We're adding it back in the future (there is an ongoing effort on that front). This should solve the first and second issue you mentioned in https://github.com/AdrienPoupa/VinylMusicPlayer/issues/323#issuecomment-711425848 ).

For the multi-disc sorting, If I'm not wrong this is a separate issue and is existing before.

**Comment by soncaokim** [comment]
The multi-disc sorting issue: https://github.com/AdrienPoupa/VinylMusicPlayer/issues/251

**Comment by CaseOf** [comment]
I'm having this issue too, I've downgraded as F-Droid allows me to, there's no album covers on the previous version though with app self covers.

**Comment by pokemonpasta** [comment]
Recently updated and now I'm having this issue too. Can someone point me in the right direction for downgrading if that'll fix it for now?

**Comment by CaseOf** [comment]
> Recently updated and now I'm having this issue too. Can someone point me in the right direction for downgrading if that'll fix it for now?

@pokemonpasta, just install previous version from F-Droid if you installed it from here before

**Comment by pokemonpasta** [comment]
> > Recently updated and now I'm having this issue too. Can someone point me in the right direction for downgrading if that'll fix it for now?
> 
> @pokemonpasta, just install previous version from F-Droid if you installed it from here before

Ah I didn't install from there before but I'll reinstall from there. Thank you

**Comment by dextertd** [comment]
Just got the 1.1.1 version installed, upon opening the app it rescanned my library and boom, albums are now correctly categorised! This is now the *perfect* music app! Cheers devs.
