### ISSUE TITLE
[Feature Request] Import Playlist File (.m3u)

### ISSUE THREAD

**Issue by SarahTehCat** [AdrienPoupa/VinylMusicPlayer#48]
Hi. 

I love this app. Very lightweight and functional.

The only thing that's missing is that although it can easily export a playlist to m3u format, it cannot import one, which makes it a lot harder to re–set up a playlist that you've already made. Especially if you have a library of 1000+ songs.

Thanks.

**Comment by megamorphf** [comment]
@SarahTehCat this app imports playlists automatically **if they are formatted correctly**.   You probably don't see you playlists, because they are using absolute paths of your computer and not your phone. 

 A solution would be to use relative paths (you keep all you music in one root directory) but you will most likely also run into issues as I did, because relative playlist support only works sometimes.

**Comment by AeliusSaionji** [comment]
I figured it out, I have to force stop the app from system settings (not the app switcher). It will scan for playlist when starting. Apparently then and only then.
