### ISSUE TITLE
Playlist problems.

### ISSUE THREAD

**Issue by fullstopslash** [AdrienPoupa/VinylMusicPlayer#502]
**Describe the bug**
Playlists can't deal with certain utf-8 characters.

**To Reproduce**
I use syncthing to synchronize  my music across devices.  Some of these files have naming schemes like "03 - †ḧΞ+ШЇⱬΛЯᶑ - CΛvs†Їc"  The player can recognize these files when I browse to them through one of the various methods like "ARTISTS" or "ALBUMS" and even displays them correctly. BUT in the playlist dialog the files are removed from display altogether. Also, If I add the file to a new playlist manually it isn't formatted correctly when I sync it back to other devices. 

**Expected behavior**
Vinyl should work with utf-8 characters in the app as well as playlists. 

 - Vinyl Music Player Version:
1.3.0

**Comment by soncaokim** [comment]
Are you referring to the cross device m3u files synchronisation ?

To pin down where the problem is, is this playlist synchronization work with other media players on Android?

And this source https://en.m.wikipedia.org/wiki/M3U suggests that M3U doesnt support unicode, so you'll need to probably to investigate on that as well.

I am not at all familiar with M3U format, so sorry if I overlooked something.

**Comment by fullstopslash** [comment]
I started having other issues with certain filesystems not liking utf-8 characters as well. You're also right about m3u not supporting utf-8, mpd simply obediently  copies over utf-8 characters. I've fixed this by changing all filenames to complient ascii characters.
